# Build stage
FROM node:lts-alpine as build-stage
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from the correct path
COPY /frontend/package*.json ./

# Install dependencies
RUN npm update npm install

# Copy the rest of the application files
COPY frontend ./

# Build the app
RUN npm run build

# Production stage with Nginx
FROM nginx:stable-alpine as production-stage

# Copy the built files to Nginx
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/
COPY /docker_frontend/nginx/nginx.conf /etc/nginx/nginx.conf
#COPY /docker_frontend/nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for Nginx
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]